#=================================================================================================================================================
#chaoscontrolmon.ps1
#=================================================================================================================================================
#This PowerShell script was designed to monitor local hard disks on Windows systems and send a Gotify notification so manual review would not be needed.
#Compatible with Windows 7 (PowerShell 2.0+), Windows 10, Windows 11, and Windows Server.
#The script assumes CrystalDiskInfo is installed so calls to its CLI utility (DiskInfo64.exe /CopyExit) can be made to generate a SMART report for parsing.
#It should be ran with a single argument as the disk number to monitor. For example: '.\chaoscontrolmon.ps1 -DiskNumber 0'
#If no argument is supplied or the specified disk cannot be detected, the script defaults to disk 1.
#The script is designed to be ran as Administrator and called via Task Scheduler.
#Example Task Scheduler settings:
 #Action:
  #Start a program
 #Program/script:
  #cmd.exe
 #Arguments:
  #/c C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File "C:\Storage\Scripts\chaoscontrolmon.ps1" > "C:\ProgramData\chaoscontrolmon\debug.log" 2>&1
 #Start in (optional):
  #C:\Storage\Scripts
#If running directly in Powershell, you may need to first run the following command to unrestrict:
 #Set-ExecutionPolicy Unrestricted -Scope CurrentUser
#=================================================================================================================================================

#=================================================================================================================================================
#Variables
#=================================================================================================================================================
#Initialize the disk number variable and set to 1 by default:
param(
    [int]$DiskNumber = 1
)

#This is the directory which saved snapshots are placed for comparison:
$DataDir = "C:\ProgramData\chaoscontrolmon"

#CrystalDiskInfo install path:
$CDIPath = "C:\Program Files\CrystalDiskInfo"
#CrystalDiskInfo CLI executable:
$CDIExe = Join-Path $CDIPath "DiskInfo64.exe"
#CrystalDiskInfo output file (generated by /CopyExit):
$CDIReport = Join-Path $CDIPath "DiskInfo.txt"

#Gotify base URL:
$GotifyUrl = "notify.domain.com"
#Gotify token:
$GotifyToken = "H4HG0771M"

#SMART attributes to monitor (matched case-insensitively against the CrystalDiskInfo report):
$WatchAttrs = @(
    "Uncorrectable Sector Count"
    "Wear Leveling Count"
    "SSD Life Left"
    "Percent Lifetime Remain"
    "Percentage Used"
    "Media and Data Integrity Errors"
    "Ultra DMA CRC Error Count"
    "Media Wearout Indicator"
    "Reallocated Sector Count"
    "Reported Uncorrectable Errors"
    "Current Pending Sector Count"
    "Offline Uncorrectable"
    "Critical Warning"
    "Available Spare"
    "Reallocated Sectors Count"
    "Health Status"
)

#=================================================================================================================================================
#SMART Data Collection
#=================================================================================================================================================
#Specify per-device baseline file (e.g. disk1.prev.txt, disk2.prev.txt):
$PreviousFile = Join-Path $DataDir "disk$DiskNumber.prev.txt"

#Create the directory specified if it does not yet exist else do nothing if it does exist:
if (-not (Test-Path $DataDir)) {
    New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
}

#Run CrystalDiskInfo CLI from its own directory to generate the report file:
Push-Location $CDIPath
& $CDIExe /CopyExit | Out-Null
Pop-Location

#Wait briefly for the file to be written:
Start-Sleep -Seconds 5

#Read the full report:
$FullReport = Get-Content -Path $CDIReport

#Parse out the section for the specified disk number:
#CrystalDiskInfo separates disks with headers like " (01) Samsung SSD 870 EVO 1TB" where (01) is the disk number:
$InTargetDisk = $false
$DiskData = @()
$DiskHeader = ""

foreach ($Line in $FullReport) {
    #Check for disk header lines containing the disk number in parentheses:
    if ($Line -match "^\s*\((\d+)\)\s+(.+)$") {
        $FoundDiskNum = [int]$Matches[1]
        if ($FoundDiskNum -eq $DiskNumber) {
            $InTargetDisk = $true
            $DiskHeader = $Line.Trim()
            $DiskData += $Line
            continue
        } elseif ($InTargetDisk) {
            #Hit the next disk section, stop collecting:
            break
        }
    }
    if ($InTargetDisk) {
        $DiskData += $Line
    }
}

#Build regex pattern from the watch list:
$Pattern = ($WatchAttrs | ForEach-Object { [regex]::Escape($_) }) -join '|'

#Filter to only the watched attributes:
$Current = $DiskData | Where-Object { $_ -match $Pattern }

#If no data was found for the specified disk and it was not disk 1, fall back to disk 1:
if (-not $Current -and $DiskNumber -ne 1) {
    $DiskNumber = 1
    $PreviousFile = Join-Path $DataDir "disk$DiskNumber.prev.txt"
    $InTargetDisk = $false
    $DiskData = @()
    $DiskHeader = ""

    foreach ($Line in $FullReport) {
        if ($Line -match "^\s*\((\d+)\)\s+(.+)$") {
            $FoundDiskNum = [int]$Matches[1]
            if ($FoundDiskNum -eq $DiskNumber) {
                $InTargetDisk = $true
                $DiskHeader = $Line.Trim()
                $DiskData += $Line
                continue
            } elseif ($InTargetDisk) {
                break
            }
        }
        if ($InTargetDisk) {
            $DiskData += $Line
        }
    }

    $Current = $DiskData | Where-Object { $_ -match $Pattern }
}

#If the previous file does not exist, this is identified as the first run so a snapshot is taken and the script exits:
if (-not (Test-Path $PreviousFile)) {
    $Current | Out-File -FilePath $PreviousFile -Encoding UTF8
    exit 0
}

#=================================================================================================================================================
#Comparison and Notification
#=================================================================================================================================================
#Compare current SMART data against previous baseline:
$Previous = Get-Content -Path $PreviousFile

#If the identified parameters in the previous snapshot and the current snapshot are not the same:
$Diff = Compare-Object -ReferenceObject $Previous -DifferenceObject $Current
if ($Diff) {
    #Format the differences into a readable string:
    $DiffMsg = ($Diff | ForEach-Object {
        $Indicator = $(if ($_.SideIndicator -eq "=>") { "[NEW]" } else { "[OLD]" })
        "$Indicator $($_.InputObject)"
    }) -join "`n"

    #Update baseline with new snapshot:
    $Current | Out-File -FilePath $PreviousFile -Encoding UTF8

    #Send Gotify notification with the diff:
    curl.exe -X POST -fs -o nul --retry 1 "https://${GotifyUrl}/message?token=${GotifyToken}" -F "title=Chaoscontrolmon: Disk ${DiskNumber} changed (${DiskHeader})" -F "message=${DiffMsg}" 2>&1 | Out-Null
}
